### ISSUE TITLE
Web ethics, psychological concerns

### ISSUE THREAD

**Issue by ghost** [tessalt/echo-chamber-js#11]
Web development or web design does have a psychological part besides the technical part, and this library is intended to give the illusion to the user that he engages with the website by commenting it.

It clearly has the intent to dupe or trick the end-user, as no indication is given that his/her message will not be sent through the network.  

In the ReadMe, the library is even described as an alternative to Disqus. But apart from toying, developing or prototyping, is there a real value of using it on a public-facing website ? 

Such library seems to rise ethical concerns about the relationship between the maintainer of the website and the end-user. It is promoting relationships based on duping another, that is, a form of irresponsability and indifference... Is it any good ? Just asking to myself.

It is not because it is internet that human interactions should be this way. Or if it is a general way of thinking about human interactions, isn't it a bit absurd ? Once again, just asking to myself, and thinking aloud.

**Comment by carpii** [comment]
I would like to see this library integrated with Github Issues

**Comment by riccardoscalco** [comment]
It can be used for personal notes. Anyway, I agree it should be clear that the comments are not visible to others.

**Comment by ab34** [comment]
Yes, technically, it can be used as a personal note widget for the end-user. The issue I guess was about how this widget is presented as an alternative to regular comments system... But perhaps it was just a joke from the author...

**Comment by hendrikswan** [comment]
Yeah, I was also surprised by the readme, why would one want comments that aren't published anywhere than to localstorage? Not sure what the purpose of this repo is.

**Comment by michaelowens** [comment]
README states very clearly it's saved in localStorage and the writing style is kind of jokingly. Maybe you guys shouldn't take it so serious.

:+1: what @carpii said

**Comment by florianletsch** [comment]
![That's the joke](http://i1.kym-cdn.com/entries/icons/original/000/012/132/thatsthejoke.jpg)

**Comment by mkzero** [comment]
![125115764586949097_1393725308](https://cloud.githubusercontent.com/assets/360964/8696999/a8a69d74-2af1-11e5-8225-f113e1e32a4d.jpg)

**Comment by Inlustra** [comment]
Why not use this as a form of banning? The ethical concerns need not be a worry if the only person affected by this isn't being ethical.

**Comment by leejinhuey** [comment]
this issue is a joke

**Comment by amogharakali** [comment]
@lnlustra
That's a bit dangerous, no? At least now, when someone gets punished through a ban or by criticism, both sides (users and admin) have the same information about what's happened. Then people can debate about whether the punishment was ethical or not. But with this, some commentators may not even realise they've been cut out of the main discussion. 

Imagine doing this, for example, on a government webpage soliciting feedback on a public project or government scheme. Or on an internal company forum during a discussion on company policy. The moderators suddenly get far too much power. 

But yes, with a bit of design, I agree with riccardoscalco that this is a good way of doing things like taking notes.

**Comment by florianletsch** [comment]
@amogharakali reddit actually uses a system like this for spam accounts, it's called a shadowban.

anyway, this issue is ridiculous

**Comment by twosticks** [comment]
"Your comments are sensitive to us. We guarantee that only you will be able to read them."

**Comment by renestalder** [comment]
Made my day. Most perfect answer, @carpii.

**Comment by joshlewis** [comment]
It's a joke until people start using it, because (I presume) it actually works. Then it's not so funny anymore.

**Comment by Discordanian** [comment]
Because people are entitled to having their comments viewed by others???     90%+ of comments are just awful.  Joke or not this is actually useful.  It gives trolls a safe outlet for their vitriol without inflicting it on others.  And if someone else leaves an earnest comment it gets ignored.  How is that different than most of 'actual' comments?

**Comment by rachelnicole** [comment]
![im here and i have an opinion](http://i.imgur.com/MVgC4gS.jpg)

**Comment by dcousineau** [comment]
![](http://vignette2.wikia.nocookie.net/saintsrow/images/6/68/Professor_Genki's_Super_Ethical_Reality_Climax.jpg/revision/latest/scale-to-width-down/640?cb=20120803024123)

**Comment by jennschiffer** [comment]
"Once again, just asking to myself, and thinking aloud."

yeah so github hasn't integrated echochamber.js (yet) so you're not actually asking to yourself and just thinking aloud right now.

**Comment by TheReverend403** [comment]
I have a feeling the only people complaining about this are the people it's intended to be used on. :)

**Comment by millette** [comment]
Why am I the only one commenting on this thread? It's important, people!

**Comment by virtadpt** [comment]
@carpii :+1:

**Comment by Trismegiste** [comment]
the creator of this lib has just won the internet today :+1: 

Sturgeon's law applied to comments ? FUCK YEAH !

**Comment by indus** [comment]
"wontfix" 😆

**Comment by kylepaulsen** [comment]
What if this entire time, something like echo-chamber has always been used on sites and right now I'm just responding to a bunch of fake comments!? :-o

Well :+1: anyway... (if anyone can see this)

**Comment by th3m4ri0** [comment]
But Kyle, how am I supposed to know you are not another generated comment? Am I only talking to myself? Am I even real? I might live in the Matrix.

**Comment by ab34** [comment]
Fake lives, so why not fake comment boxes...

**Comment by emory** [comment]
Personally I think this is the greatest honeypot for stupid ever devised. 

Between this and Shut-up.css the web is dangerously close to becoming useful again. I don't think I care if I never see another comment from Angry McBumpkin and his buddies on the Compound ever again, they just recently figured out how to mash keys and defeat the mighty CAPTCHA on my Contact form.

**Comment by ab34** [comment]
In the eventuality that this repository is used beyond the field of experimentation and leisure, in real production environments, here some points I'd like to share if someone cares about them. 

I'm sure that many people don't care about thinking too much about the implications of this way of doing, and will find that this repository is a good and easy solution to their commenting needs, but for the ones who care a bit about what they are doing, it rises multiple interrogations which may enforce the idea that it is an incorrect usage of technology.

After all, it is not because something is feasible technically that it is good practice and that it does not cause detrimental side-effects. Technology is only useful when it is used wisely in the field of relationships and environment. And when a technology has more detrimental effects than benefits, it is safe to say that there is no need to use it, or that it is an incorrect solution to a problem that may be solved in other ways.

Internauts using a comment box expect that someone will read their messages, and this is the foundation of the web than to have places where people can interact with each others around certain thematics or more generally. Here, this library intends to mislead all users of a website, indifferently, by removing this expectation which is foundational of the web.

It is a bit like having a false mailbox that misleads the user and make him believe that the email he/she wrote has been sent but no one ever replied. It is not only dishonest, but it has unknown implications, legal, relational and psychological, and I can't think of any major web consortium, or any serious web company that may think that it can be a good practice to induce internauts in errors with such web components.

The web is already composed of a tremendous amount of dumb websites, either unmaintained, either auto-generated, and a library like this one gives further tools to unthoughtful web designers to create more and more of those websites, while misleading the users in making them believe that it has interaction functionality via a comment system. The web may not need more dumb websites, but higher quality sites, with the expectation of them to be honest and not inducing the internauts in false beliefs or other deceptive assumptions.

For legitimate websites willing to use this library, it will necessarily be detrimental for them when the trickery will be known by users. Because if a website dupes a user with a non genuine comment system, how can then the user trust the very content of the website ?  

At the first clean-up of their localcache, users may eventually perceive the trickery, and I don't give much legitimity from the user's point of view to websites being engaged, in their very structure, with such way of misleading those for whom the website is intended.

Thanks for listening.

**Comment by millette** [comment]
http://data2.whicdn.com/images/48673540/large.gif

**Comment by johndkane** [comment]
aka hellbanning https://en.wikipedia.org/wiki/Hellbanning

**Comment by ab34** [comment]
@millette, because when you faced hell or terrible things without escaping and with utter seriousness, by embracing and understanding it fully and totally, then there is freedom from it and the possibility for life to be fun again.

**Comment by prometheas** [comment]
@tessalt - this is my favorite repo, ever.

@ab34 - come on, now.

**Comment by dcousineau** [comment]
😂😂😂😂

**Comment by jacksonofalltrades** [comment]
This is the dumbest complaint I've ever seen. Is this plugin misleading to users? Yes. But whoever owns the website gets to control what users do on it, period. How many corporate websites do things with user data that we don't know about? And we *know they do this* and still keep using the sites. So from that standpoint simply being ignored when writing comments is nothing compared to the nasty things people are doing with our user data.

Also, I think eventually, if someone really wanted people to respond to their comments, they'll go find another website to comment on that isn't using this.

I like the idea of being able to conditionally apply this to only some users, since again, the owner of the site should get to control user behavior.

**Comment by qwrrty** [comment]
hehehe they mad.

**Comment by virtadpt** [comment]
The dir need for this website extension is now writ large.

**Comment by virtadpt** [comment]
@qwrrty It's because they know it's specifically for them, and they're terrified they won't be heard anymore.  Not your site, not your sandbox, not your rules.

**Comment by ab34** [comment]
@jacksonofalltrades I think that web developers can manage (I prefer the word 'manage' to the word 'control') what users can do on their website ***without*** misleading them. This was the whole point of the issue in fact, nothing less, nothing more. 

If one does not wish people to comment on one's website, then one could simply avoid to put a comment box in it, isn't it right ? Why trying to dupe **all** users to think that there is something that is not there ? It is just what was asked, suggested there.

Now, I think the whole idea, concept behind this library is based on that dupery; and it has been said that it won't be fixed, so the issue is closed to me. I'm not trying here to convince anyone of doing this or that, as each one should act and decide for themselves.

But it is funny nevertheless to observe how many people here tried to turn the issue into derision whereas it is legitimate and serious to ask those questions to oneself. Surely (and nothing personal of course, as I don't know anyone here personally), some people may be so used to have relationships based on a more or less subtle exploitation, manipulation or wish to control others, that they don't really care about lying, duping or not being honest. 

In that case, then there is not much to do about it. It is each one's life, and each one has to be aware of how they relate to another for themselves. Self-knowledge is maturity.

I know that people generally may not particularly care about relationships and rather blame the others or the governments and so on, but I think personally that society begins in the relationship one has with another, and it begins where one is. So if one relates with another by means of trickery, one creates a society that is unsafe and where there is no trust.

Also, as you pointed out, the whole business world is also made of some forms or others of dupery and exploitation. But it should not be a pretext to act like that oneself. In the means is the end. And if no one can prevent people to do tricks to each others, it is nevertheless possible to not act that way oneself, individually, and it was just the position that was expressed here via this issue.

I think relationships are important and deserve attention, even if it is the relationship that one has indirectly with end-users of a website. It just means to present correct information and not voluntarily mislead people.

Sorry if I wrote a lot. Anyway, I suppose people reading here are interested into the issue, otherwise they may pass to something else. I personally like to go deep into any thing that draws my attention. Most people are not used to think, discuss, or to listen to what another human being has to say, as nowadays the trends are to sites like twitter which diminish the capacity to think by forcing their users to express themselves briefly. But it is yet another issue...

**Comment by rachelnicole** [comment]
oh shut up already jfc

**Comment by rachelnicole** [comment]
Like you're clearly not even a github user you're the annoying equivalent of a egg on twitter.

**Comment by ab34** [comment]
Yes, sure, @rachelnicole. As the discussion turns on personalizing, it is good to close it. Thanks.
